stages:
  - build
  - deploy

.deploy:
  stage: deploy
  image: enix/ci-toolbox:1.23
  before_script:
    - kubectl version
    - helm version
  script:
    - cd deploy
    - helmfile template
    - helmfile lint
    - helmfile sync

build-libre-chat-pr:
  image: docker:24
  stage: build
  variables:
    APP: "libre-chat"
  before_script:
    - i=0; while [ "$i" -lt 12 ]; do docker info && break; sleep 5; i=$(( i + 1 )) ; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - apk add git
  script:
    - git clone https://github.com/danny-avila/LibreChat.git
    - cd LibreChat
    - docker build -t "$CI_REGISTRY_IMAGE/${APP}:$CI_COMMIT_SHA" -f ./Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE/${APP}:$CI_COMMIT_SHA"

deploy-dev:
  extends: .deploy
  stage: deploy
  variables:
    KUBE_NAMESPACE: "librechat"
    INGRESS_CLASS: "public"
    URL: "librechat.example.com"
    TAG: "$CI_COMMIT_SHA"
    HELM_EXPERIMENTAL_OCI: 1
  environment:
    name: k8s
    url: https://librechat.example.com