apiVersion: v2
name: librechat
description: A Helm chart used to deploy the service librechat owned by dope.
type: application
version: 0.1.0
dependencies:
  - name: meilisearch
    repository: https://meilisearch.github.io/meilisearch-kubernetes
    version: 0.3.0
    condition: meilisearch.enabled
