apiVersion: v2
name: librechat
description: Frontend for AI endpoints
type: application
version: 1.0.0
dependencies:
  - name: meilisearch
    repository: https://meilisearch.github.io/meilisearch-kubernetes
    version: 0.4.0
    condition: meilisearch.enabled
  - name: redis
    version: 18.7.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
  - name: mongodb
    version: 14.6.1
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: mongodb.enabled
